env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "prettier"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
rules: {
  "no-unused-vars": error,
  "sort-imports": "error",
  "prettier/prettier": "error",
}
